### ISSUE TITLE
Dotenv values containing spaces must be surrounded by quotes.

### ISSUE THREAD

**Issue by tylerwiegand** [RobDWaller/wordpress-salts-generator#2]
```
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php:76
```

Anytime I install wp via command line (as I usually do) it doesn't like the spaces in these generated salts. Using the "official" doesn't present this issue, as they don't seem to include spaces in the salts.

Example -- these salts:
```
AUTH_KEY = '?+$N\p:bAXBN!2n`xdJvGa3O//S]*9!rA}BoDI1V&Qo8vfBy3!iTB;J-YYcaS*rW'
SECURE_AUTH_KEY = 'w@HyRw:$rAZ2"ePbIT5(N*oEfAOQu(IlndGY0QNA=Z^>k9H,G5d^$IY,cc.P_h\N'
LOGGED_IN_KEY = '<UA2E5O !OM9,[_4!x4G6@Ee(N'^2$UXRi9y!rff\9ir>=X:1c]5k/hFoAFE>h&4'
NONCE_KEY = ']Vuo"N,gWdo0z(:I sny!Gw;BK00tof9M$u2Fl41dIJ&},wja'Jt*MC%ef]]SyL@'
AUTH_SALT = 'Q$$I9dvY4&!|?(oWKW<8b+iWb\mD>1_Llx/&Kdy_\dab_\,PtSg9"rM[KfTOIZtb'
SECURE_AUTH_SALT = 'rLu,71kGUiiq-(S^f0F=;5,t< f9l*-%s*.4gt?gKLNcm)q2!%TR#jP=b[Vhld0O'
LOGGED_IN_SALT = 'F)Ud&*/*&Kd8;L~`Sx 55fugy@CmsnaaBZRAe7T0e!W1hJlUB&|qDJIJefU2t2I!'
NONCE_SALT = 'Omz/e3LGhT)T_).xPeg*)=xh?5|2"<0u=$5,75%HIH!4rTY25UH}.j12aBn?@L*x'
```
produce this output: 
```
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php:76
Stack trace:
#0 [internal function]: Dotenv\Parser::Dotenv\{closure}(Array, '!')
#1 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php(84): array_reduce(Array, Object(Closure), Array)
#2 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(237): Dotenv\Parser::parseValue(''<UA2E5O !OM9,[...')
#3 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(151): Dotenv\Loader->sanitiseVariableValue('LOGGED_IN_KEY', ''<UA2E5O !OM9,[...')
#4 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(128): Dotenv\Loader->processFilters('LOGGED_IN_KEY', ''<UA2E5O !OM9,[...')
#5 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(323): Dotenv\Loader->normaliseEnvironmentVariable('LOGGED_IN_KEY = in /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php on line 76

Fatal error: Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php:76
Stack trace:
#0 [internal function]: Dotenv\Parser::Dotenv\{closure}(Array, '!')
#1 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php(84): array_reduce(Array, Object(Closure), Array)
#2 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(237): Dotenv\Parser::parseValue(''<UA2E5O !OM9,[...')
#3 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(151): Dotenv\Loader->sanitiseVariableValue('LOGGED_IN_KEY', ''<UA2E5O !OM9,[...')
#4 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(128): Dotenv\Loader->processFilters('LOGGED_IN_KEY', ''<UA2E5O !OM9,[...')
#5 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(323): Dotenv\Loader->normaliseEnvironmentVariable('LOGGED_IN_KEY = in /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php on line 76
```
and as you can see the "LOGGED_IN_KEY" has a space and then an !

If I surround every like with double quotes, I get this output, and I'm not sure why:
```
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php:76
Stack trace:
#0 [internal function]: Dotenv\Parser::Dotenv\{closure}(Array, 'e')
#1 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php(84): array_reduce(Array, Object(Closure), Array)
#2 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(237): Dotenv\Parser::parseValue('"w@HyRw:$rAZ2"e...')
#3 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(151): Dotenv\Loader->sanitiseVariableValue('SECURE_AUTH_KEY', '"w@HyRw:$rAZ2"e...')
#4 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(128): Dotenv\Loader->processFilters('SECURE_AUTH_KEY', '"w@HyRw:$rAZ2"e...')
#5 /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Loader.php(323): Dotenv\Loader->normaliseEnvironmentVariable('SECURE_AUTH in /Users/me/sites/client/vendor/vlucas/phpdotenv/src/Parser.php on line 76
```
If I switch to the "official" salts, this problem goes away entirely. This library used to work for me, so I can only imagine an update to the Dotenv library has produced this issue.

Thank you! Looking forward to a "fix."

**Comment by RobDWaller** [comment]
Apologies it's taken a little while for me to get round to this, been v busy, I should have the fix ready by Monday.

**Comment by RobDWaller** [comment]
Closing this ticket after releasing 0.2.0, which should fix the problems raised. 
https://github.com/RobDWaller/wordpress-salts-generator/releases/tag/0.2.0

Thanks for your help on this and a bigger tidy up release will come in the next few weeks I hope
